language: ruby
sudo: false
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - 2.1
  - 2.0
gemfile:
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_3.2.gemfile
matrix:
  exclude:
    - rvm: 2.5.1
      gemfile: gemfiles/activerecord_4.1.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/activerecord_4.0.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/activerecord_3.2.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/activerecord_4.1.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/activerecord_4.0.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/activerecord_3.2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_5.2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_5.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_5.0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activerecord_5.2.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activerecord_5.1.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activerecord_5.0.gemfile
